-- Vertretungsplan-Eintraege (einzelne Vertretungszuweisungen)
CREATE TABLE IF NOT EXISTS substitutions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timetable_setting_id INT NOT NULL,
    date DATE NOT NULL COMMENT 'Konkretes Datum der Vertretung',
    day_of_week TINYINT NOT NULL COMMENT '1=Montag, ..., 6=Samstag',
    slot_number INT NOT NULL COMMENT 'Einheitsnummer',
    class_id INT NOT NULL,
    absent_teacher_id INT NOT NULL COMMENT 'Abwesende Lehrkraft',
    substitute_teacher_id INT NULL COMMENT 'Vertretende Lehrkraft (NULL bei Entfall)',
    absence_teacher_id INT NULL COMMENT 'Verknuepfung zur Krankmeldung',
    subject VARCHAR(100) NULL COMMENT 'Fach',
    room VARCHAR(50) NULL COMMENT 'Raum',
    notes TEXT NULL COMMENT 'Hinweise',
    is_cancelled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = Entfall',
    created_by INT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_substitution (timetable_setting_id, date, slot_number, class_id, absent_teacher_id),
    INDEX idx_sub_date (timetable_setting_id, date),
    INDEX idx_sub_substitute (substitute_teacher_id, date),
    INDEX idx_sub_absent (absent_teacher_id, date),
    CONSTRAINT fk_sub_setting FOREIGN KEY (timetable_setting_id) REFERENCES timetable_settings(id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_absent_teacher FOREIGN KEY (absent_teacher_id) REFERENCES teachers(id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_substitute_teacher FOREIGN KEY (substitute_teacher_id) REFERENCES teachers(id) ON DELETE SET NULL,
    CONSTRAINT fk_sub_absence FOREIGN KEY (absence_teacher_id) REFERENCES absences_teachers(id) ON DELETE SET NULL,
    CONSTRAINT fk_sub_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
